
services:
  postgres:
    container_name: zkstack-postgres
    image: postgres:14
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=block-explorer
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: unless-stopped

  explorer-app:
    container_name: zkstack-explorer-app
    image: "matterlabs/block-explorer-app"
    ports:
      - '3010:3010'
    depends_on:
      explorer-api:
        condition: service_started
    volumes:
      - ./config/explorer-app.config.js:/usr/src/app/packages/app/dist/config.js
    restart: unless-stopped
  explorer-worker:
    container_name: zkstack-explorer-worker
    image: "matterlabs/block-explorer-worker"
    environment:
      - PORT=3001
      - LOG_LEVEL=verbose
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=block-explorer
      - BLOCKCHAIN_RPC_URL=http://zkstack-apis:3051
      - DATA_FETCHER_URL=http://explorer-data-fetcher:3040
      - BATCHES_PROCESSING_POLLING_INTERVAL=1000
    restart: unless-stopped
  explorer-api:
    container_name: zkstack-explorer-api
    image: "matterlabs/block-explorer-api"
    environment:
      - PORT=3020
      - METRICS_PORT=3005
      - LOG_LEVEL=verbose
      - NODE_ENV=development
      - CONTRACT_VERIFICATION_API_URL=http://zkstack-apis:3070
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/block-explorer
    ports:
      - '3020:3020'
    depends_on:
      explorer-worker:
        condition: service_started
        restart: true
    restart: unless-stopped
  explorer-data-fetcher:
    container_name: zkstack-explorer-data-fetcher
    image: "matterlabs/block-explorer-data-fetcher"
    environment:
      - PORT=3040
      - LOG_LEVEL=verbose
      - NODE_ENV=development
      - BLOCKCHAIN_RPC_URL=http://zkstack-apis:3050/
    ports:
      - '3040:3040'
    restart: unless-stopped

volumes:
  postgres:
